[package]
name = "wallet-tester"
version = "1.0.0"
description = "Created with Anchor"
edition = "2018"

[features]
mock-clock = []

[lib]
crate-type = ["cdylib", "lib"]
name = "wallet_tester"

[dependencies]
anchor-lang = {workspace = true, features = ["init-if-needed"]}
